### PR TITLE
Garbage Collector, Беляев-Маркелов

### PR DESCRIPTION
**Pull request by StasBel**
Добавили к тестам valgrind. В runtime'e появился collector.cpp с реализацией сборщика, а также подстроился под изменения builtins.cpp. Часть компилятора научилась вызывать функции gc, а также динамически поддерживать для каждого значения на стеке еще одно - интересно ли оно для сборщика (int - нет, string/array - да).
Циклических зависимостей нет by design.

### CODE REVIEW

**Comment by danyaberezun** [comment]
Почему valgrind выдает столько ошибок на 30 тесте?

**Comment by darkpeaceduck** [comment]
@danyaberezun 
 ?
`../rc.native -o test030.expr && cat test030.input | valgrind --leak-check=full --show-leak-kinds=all --show-reachable=no --error-exitcode=1 --undef-value-errors=no  ./test030 > test030.log && diff  test030.log orig/test030.log
==13691== Memcheck, a memory error detector
==13691== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==13691== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==13691== Command: ./test030
==13691== 
==13691== 
==13691== HEAP SUMMARY:
==13691==     in use at exit: 18,944 bytes in 1 blocks
==13691==   total heap usage: 121 allocs, 120 frees, 21,548 bytes allocated
==13691== 
==13691== LEAK SUMMARY:
==13691==    definitely lost: 0 bytes in 0 blocks
==13691==    indirectly lost: 0 bytes in 0 blocks
==13691==      possibly lost: 0 bytes in 0 blocks
==13691==    still reachable: 18,944 bytes in 1 blocks
==13691==         suppressed: 0 bytes in 0 blocks
==13691== Reachable blocks (those to which a pointer was found) are not shown.
==13691== To see them, rerun with: --leak-check=full --show-leak-kinds=all
`

**Comment by danyaberezun** [comment]
@darkpeaceduck

../rc.native -o test030.expr && cat test030.input | valgrind --leak-check=full --show-leak-kinds=all --show-reachable=no --error-exitcode=1 --undef-value-errors=no ./test030 > test030.log && diff test030.log orig/test030.log

==451== Memcheck, a memory error detector
==451== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==451== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==451== Command: ./test030
==451== 
==451== Invalid read of size 4
==451==    at 0x804C633: std::_Rb_tree<RegisterItem*, RegisterItem*, std::_Identity<RegisterItem*>, std::less<RegisterItem*>, std::allocator<RegisterItem*> >::begin() const (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x804BF3B: std::multiset<RegisterItem*, std::less<RegisterItem*>, std::allocator<RegisterItem*> >::begin() const (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x804BDBB: RegisterItem::print_info() (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x804BE06: RegisterItem::print_info() (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x804B957: Tgc_ref (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8048FB8: ??? (test030.s:462)
==451==    by 0x8049819: ??? (test030.s:1151)
==451==    by 0x426F195: (below main) (in /usr/lib32/libc-2.24.so)
==451==  Address 0x4418f3c is 20 bytes inside a block of size 32 free'd
==451==    at 0x402D6FB: operator delete(void*) (vg_replace_malloc.c:576)
==451==    by 0x804BA78: Tgc_collect (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8049DF6: Larrget (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8048F2C: ??? (test030.s:415)
==451==    by 0x8049819: ??? (test030.s:1151)
==451==    by 0x426F195: (below main) (in /usr/lib32/libc-2.24.so)
==451==  Block was alloc'd at
==451==    at 0x402C813: operator new(unsigned int) (vg_replace_malloc.c:328)
==451==    by 0x804B709: gc_malloc(unsigned int) (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8049C52: arralloc(int) (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8049CA1: Larrmake (in /home/danya/projects/sample-compiler/regression/test030)
==451==    by 0x8048E7D: ??? (test030.s:357)
==451==    by 0x8049819: ??? (test030.s:1151)
==451==    by 0x426F195: (below main) (in /usr/lib32/libc-2.24.so)

/* a lot of similar errors */

==451== 
==451== 
==451== HEAP SUMMARY:
==451==     in use at exit: 0 bytes in 0 blocks
==451==   total heap usage: 123 allocs, 123 frees, 29,740 bytes allocated
==451== 
==451== All heap blocks were freed -- no leaks are possible
==451== 
==451== For counts of detected and suppressed errors, rerun with: -v
==451== ERROR SUMMARY: 156 errors from 31 contexts (suppressed: 0 from 0)

**Comment by darkpeaceduck** [comment]
@danyaberezun 

Поставил 3.12 valgrind (был 3.11) - не воспроизвелось.

Можете написать версию компиляторов ?
У меня такие 

ocaml --version
The OCaml toplevel, version 4.03.0

g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc --version
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ar --version
GNU ar (GNU Binutils for Ubuntu) 2.25.1
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty

ld --version
GNU ld (GNU Binutils for Ubuntu) 2.25.1
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

Система:

uname -a
Linux scomp 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

---------------------------
Какая конфигурация у Стаса я не знаю, он напишет, как увидит наверно. Насколько я знаю, у него тоже без ошибок воспроизводится.
Или может быть - Вы в контейнере запускаете ? Если да, то можно его расшарить как нибудь ?

**Comment by danyaberezun** [comment]
@darkpeaceduck

➜ valgrind --version
valgrind-3.12.0
➜ ocaml --version
The OCaml toplevel, version 4.03.0
➜ gcc --version
gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  ar --version
GNU ar (GNU Binutils) 2.27
Copyright (C) 2016 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
➜  ld --version
GNU ld (GNU Binutils) 2.27
Copyright (C) 2016 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by darkpeaceduck** [comment]
@danyaberezun 
какой то факап пофиксили, не улучшилось ? Сейчас обновлю gcc

**Comment by danyaberezun** [comment]
Nope.

==10291== For counts of detected and suppressed errors, rerun with: -v
==10291== ERROR SUMMARY: 156 errors from 31 contexts (suppressed: 0 from 0)

Везде Invalid read\write of size 4

**Comment by darkpeaceduck** [comment]
@danyaberezun  поставил g++ и gcc 6.2.0 - эффект не наблюдается
сейчас поставлю 6.2.1

**Comment by darkpeaceduck** [comment]
@danyaberezun 
во, а может быть получится по ssh как нибудь расшарить ?
(например доступ только к 1 папке с репозиторием, доступ на pull, доступ на build)
а то что то ад

**Comment by darkpeaceduck** [comment]
@danyaberezun 
а где вообще найти ваш билд ?
на [офф сайте ](https://gcc.gnu.org/gcc-6/)
на их фтп после 6.2.0 сразу лежат 6.3.0

ещё нашел какой то rpm пакет
http://rpm.pbone.net/index.php3/stat/4/idpl/34670666/dir/fedora_other/com/gcc-6.2.1-1.fc25.i686.rpm.html

это оно ?

**Comment by darkpeaceduck** [comment]
@danyaberezun 
поставил из репозиториев и наконец воспроизвелось.
скоро пофиксим

**Comment by darkpeaceduck** [comment]
@danyaberezun 
вроде тесты теперь проходят

**Comment by StasBel** [comment]
@danyaberezun 
переделали, появились тесты с циклическими зависимостями

**Comment by darkpeaceduck** [comment]
@danyaberezun
добавил коду по оговоренному

**Pull request closed without merging**
